plugins {
  id 'com.android.library'
}

android {
  namespace 'tech.zekon.gui'

  defaultConfig {
    minSdk 28
    targetSdk 36
    consumerProguardFiles "consumer-rules.pro"
  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }
  compileSdk = 36
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  api 'com.googlecode.libphonenumber:libphonenumber:9.0.31'
  api 'com.google.android.material:material:1.14.0'
  implementation 'androidx.core:core:1.18.0'
  implementation 'com.google.android.play:core-common:2.0.4'
  implementation 'com.google.android.play:review:2.0.2'
}
